### ISSUE TITLE
new_types db info needed to make type interface work

### ISSUE THREAD

**Issue by ai-danno** [robison/Metrics-in-a-Box#1]
Hello, in the types.db there is no type of interface, and I can see you defined a second types.db (new_types.db) and I'm assuming you defined that there.

Can you share that definition, or even the whole file? It would be greatly appreciated.

**Comment by robison** [comment]
unfortunately, no.

**Comment by ai-danno** [comment]
That's disappointing. I was looking for just a portion of it that helped define how to hit juniper switch interfaces. Any luck on at least getting some insight on how that was defined?

**Comment by ai-danno** [comment]
Actually, you already shared it here.

Good Day sir.

**Comment by robison** [comment]
apologies for the very terse answer yesterday, presently on holiday and was surprised by someone opening an issue on this nearly four-year old repo. i'd have to go back through it and jog my memory - unless you've found what you were looking for in the commit history or somesuch?
